name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version
        id: cargo-version
        run: |
          VERSION=$(grep '^version' Cargo.toml | head -n 1 | awk -F'"' '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version extracted: $VERSION"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: uhryniuk/tally:${{ env.VERSION }}


